language: python
python:
  - "3.6"

install:
  - sudo apt-get install ninja-build
  - pip install .
  - python setup.py build
  - python setup.py build_ext --inplace
  - python setup.py bdist_wheel sdist

script:
  - pytest

branches:
  except:
  - dockerbuild
