name: build-wheels

on: [push, pull_request, workflow_dispatch]

jobs:
  build_wheels:
    env:
      # CIBW_BUILD: "cp39-* cp310-*"
      CIBW_SKIP: "cp27-* cp35-* pp27-* pp36-win32 pp36-macosx_x86_64"
      CIBW_TEST_REQUIRES: pytest pytest-trio pytest-asyncio trio curio pytest-curio
      CIBW_TEST_COMMAND: pytest -v {project}/test
      CIBW_BEFORE_BUILD_WINDOWS: bash .github/rmstuff.sh

      # macOS specific
      CIBW_ARCHS_MACOS: "universal2"
      CIBW_ENVIRONMENT_MACOS: MACOSX_DEPLOYMENT_TARGET='10.9' CMAKE_OSX_ARCHITECTURES='x86_64;arm64'
      CIBW_BUILD_VERBOSITY: 1

    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      # don't fail so we can see the results of other OSes.
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v3

      # Used to host cibuildwheel
      - uses: actions/setup-python@v3

      - name: Install/update dependencies
        run: |
          python -m pip install -U pip

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.11.2

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
